repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      exclude: "(mkdocs.yml|recipe/meta.yaml)"
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      additional_dependencies: ['types-requests']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 5e2fb545eba1ea9dc051f6f962d52fe8f76a9794  # frozen: v0.15.13
    hooks:
      # Linter
      - id: ruff-check
        args: [--fix]
      # Formatter
      - id: ruff-format
