name: anaconda-channel-guide
channels:
  - defaults
dependencies:
  - python>=3.10
  - setuptools
  - pip
  - conda
  # run
  - requests
  # test
  - pytest
  - pre-commit
  # plugins
  - pytest-cov
  - pytest-mock
