name: anaconda-channel-guide tests

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read  # to check out a private repository

jobs:
  unit-tests:
    name: Test (${{ matrix.runner }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest]
        python-version: ["310", "311", "312", "313", "314"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      PIXI_ENV: test-py${{ matrix.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          environments: ${{ env.PIXI_ENV }}

      - name: Ensure package is installed
        run: pixi reinstall --environment "${PIXI_ENV}" anaconda-channel-guide

      - name: Run tests
        run: pixi run --environment "${PIXI_ENV}" test

  build-conda:
    name: Build conda package
    needs: unit-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      PIXI_ENV: build
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          environments: ${{ env.PIXI_ENV }}

      - name: Build recipe
        run: pixi run --environment "${PIXI_ENV}" build

      - name: Upload conda package to anaconda.org
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'release') }}
        uses: anaconda/actions/upload-package@a6f488910b4a1e4f3fe01736241ca1b92b4b355a  # v0.3.1
        with:
          channel: anaconda-cloud
          force: true
          labels: ${{ github.event_name == 'push' && 'dev' || '' }}
          packages: .pixi/envs/build/conda-bld/noarch/anaconda-channel-guide-*.conda
          private: true
          target-type: anaconda.org
          token: ${{ secrets.ANACONDA_ORG_UPLOAD_TOKEN }}  # zizmor: ignore[secrets-outside-env]
